### ISSUE TITLE
Name changes

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBlocks.jl#1]
- [x] `usedbits` -> `occupied_locations`: directly follows the documentation:

> occupied locations of a given block.

I tried to make this shorter, but it has to follow the convention `locations`, or `occupied_locs`. `used` is not accurate, it sounds like this location was used before, but still available which is in contrast to what this should mean.

- [x] `block`/`parent` -> `content`: name conflict in local scope, use content instead. This method is for all blocks with a block inside, no matter it is a primitive or composite. 
- [x] `chblock` -> `chsubblocks(blk, subblk)`: make use of multiple dispatch, when the 2nd arg is a block, just treat it as chblock, since this make sense for all composite blocks ( when `chain`, `kron`, etc. have a single content block and containers only have one content block)

- [x] `addrs` is removed, it's never used.

- [x] move constant gates to module `ConstGate` (not done yet, need to discuss what kind of common gates still need to be exported out of `YaoBlockTree`, e.g `X`, `Y`, `Z`)

- [x] `matrixgate` -> `matgate`: shorter name for convenience

- [x] `measure` is used to construct `Measure` block (no conflict with `YaoBase`, but is a type pirate, which is fine)

- [x] `AddBlock` -> `Sum` to make use of `Prod`'s code, they are both binary operators, shares a lot common functionalities.

- [x] `ctrl_qubits` etc. -> `ctrl_locs`, `ctrl_val`/`val` etc. -> `ctrl_config`

updating...

**Comment by GiggleLiu** [comment]
> usedbits -> occupied_locations

`occupied_locations` is too long

> chblock -> chsubblocks(blk, subblk)

`chcontent` for consistency

> move constant gates to module `ConstGate`

Do you mean a submodule? Being a `submodule` is better than being a separate package

> matrixgate -> matgate: shorter name for convenience

`matgate` is not friendly for pronouncing, `tg` sounds strange. Comparing with `occupied_locations`, `matrixgate` is quite good. = =

> measure is used to construct Measure block (no conflict with YaoBase, but is a type pirate, which is fine)

don't understand

=========
The rest are ok.

**Comment by Roger-luo** [comment]
> matgate is not friendly for pronouncing, tg sounds strange. Comparing with occupied_locations, matrixgate is quite good. = =

`matgate` follows `mat`

> occupied_locations is too long

`occupied_locs` ?

> Do you mean a submodule? Being a submodule is better than being a separate package

module means submodule, there's no difference of `submodule` in Julia. There're only difference between `module` and `package`/`project`.

> don't understand

like `chain`, etc. you can define `Measure` with `measure` (a function). All the blocks in this package provide a corresponding lower-case method for construction for convenience (but it's not a requirement in other component package).

**Comment by GiggleLiu** [comment]
`matgate` -> matblock

`measure` is used as a function in `YaoArrayRegister`, is there any other name that can we use then?
Maybe make `measure` lazy? the problem is `measure` is different from `measure!`

**Comment by Roger-luo** [comment]
`measure` has no conflict with `YaoArrayRegister` , since `measure` has to take a register as input for registers. Or it will construct a block. (which is an operator, which make sense).

**Comment by Roger-luo** [comment]
parameters:
- [x] `iparameters` -> `parameters`: it's pretty vague to let only one letter to represent something, and `parameters` as a noun is some property of the instance (which was why I originally call it `parameters`).
- [x] `parameters` -> `allparameters`: it's more explicit to say `all` instead of just `parameters` when you return all the parameters of a block tree.

- [x] `dispatch!!` -> `popdispatch!`: `dispatch!!` itself it's a pretty weird notation in Julia, and the second `!` looks vague as well (unless you look up docs, `!` usually just mean the first argument is mutated, `!!` doesn't mean anything), `popdispatch!` reminds people this will pop the list first then dispatch what's popped out. (like `mapreduce`, it `map`s a function first, then `reduce`).

- [x] `iparameter_type` -> `param_eltype`, this is too long, and not accurate (it's the element type, not type of parameters)
- [x] `parameter_type` -> `allparam_eltype`: same as above

**Comment by GiggleLiu** [comment]
`dispatch!! -> popdispatch!`

maybe `intrinsic_parameters` can be a more explicit name for `iparameter`. `parameters` is just perfect. As a widely used interface, no one is complainting about it, a better name does not exist.

**Comment by Roger-luo** [comment]
This is done.
