### ISSUE TITLE
doc improvement of expect'

### ISSUE THREAD

**Issue by wangleiphy** [QuantumBFS/YaoBlocks.jl#124]
clarify the mathematical meaning of expect' 

https://github.com/QuantumBFS/YaoBlocks.jl/blob/master/test/autodiff/specializes.jl#L21

BTW, typo here
https://github.com/QuantumBFS/YaoBlocks.jl/blob/master/test/autodiff/specializes.jl#L43

`fideliy` -> `fidelity`

**Comment by Roger-luo** [comment]
is this resolved now? @GiggleLiu

**Comment by GiggleLiu** [comment]
yes
