### ISSUE TITLE
What does `adjcunmat` do?

### ISSUE THREAD

**Issue by jlbosse** [QuantumBFS/YaoBlocks.jl#158]
I am trying to get quantum backpropagation with GPU acceleration working for `MyCustomBlock <: YaoBlocks.PrimitiveBlock{2}`. It has only one real parameter (like e.g. a rotation gate) and in my circuits always occurs inside a `PuttBlock`. Hence the easiest solution seemed to be to write my own 
```julia
mat_back!(::Type{T}, rb::PutBlock{N,C,MyCustomBlock}, adjy, collector)
```
to replace the version in `YaoBlocks/autodiff/mat_back.jl:43`. But I don't exactly understand 
what `adjcunmat` in line 45 does and what I should do instead

**Comment by GiggleLiu** [comment]
adjcunmat is the most general “adjoint function for controlled unitary n bit gate”. It returns matrix as the gate gradients. It parameters are (adjoint of output, number of bits, control locations, control values, gate matrix, gate locations), this is a pretty low level interface.
You should rewrite this mat_back! function to make it work for gpu. collector stores the gradients, you can use pushfirst! to push a gradient into this collector.

I want to confirm are you planning to differentiating the matrix representation of a block? Or just applying it to a register?

**Comment by jlbosse** [comment]
The end goal is to make `expect'(hamiltonian, curegister => circuit)` work for a parametric circuit containing `MyCustomBlock`.

I was indeed planning to rewrite the `mat_back!` for `PutBlock{N,C,MyCustomBlock}` and now I am confused why I need some "adjoint function for controlled unitary n bit gate" at all; There are no controlled gates in the circuit but in line 45 of mat_back.jl it is called.

Maybe it is easier to ask the following: What exactly should
```julia
mat_back!(::Type{T}, rb::PutBlock{N,C,MyCustomBlock}, adjy, collector) where {T,N,C}
```
do?

**Comment by GiggleLiu** [comment]
Then you probably need to implement `apply_back!` rather than `mat_back!`. https://github.com/QuantumBFS/YaoBlocks.jl/blob/master/src/autodiff/apply_back.jl

> There are no controlled gates in the circuit but in line 45 of mat_back.jl it is called.

I do not mean you have to overwrite `adjcunmat`. I was answering what it is. It is a fallback implementation.

The `mat_back!` is only used when you back propagate the matrix representation of a function. It is not expected to be called here. If you can provide a minimum working example, I can show you which interface to overwrite in more detail.

**Comment by jlbosse** [comment]
Yes, it indeed looks like I want to implement `apply_back!`. My custom gate is `exp(-1im * H * t)` with `H = XX + YY + ZZ` (the Heisenberg interaction). I figured I could do essentially the same as is done for rotation gates in `apply_back.jl:39ff` and `apply_back.jl:135ff`.  So:

```julia
@const_gate Heisenberg::ComplexF64 = [1 0 0 0; 0 -1 2 0; 0 2 -1 0; 0 0 0 1]

function YaoBlocks.AD.backward_params!(st, block::PutBlock{N, MyCustomBlock}, collector) where {N}
    out, outδ = st
    in = copy(out)
    ham = put(N, block.locs => Heisenberg)
    g = state(in |> ham) ⋅ state(outδ)
    pushfirst!(collector, -imag(g))
    nothing
end

function YaoBlocks.AD.apply_back!(st, block::PutBlock{N, MyCustomBlock}, collector) where {N}
    out, outδ = st
    adjblock = block'
    YaoBlocks.AD.backward_params!((out, outδ), block, collector)
    in = apply!(out, adjblock)
    inδ = apply!(outδ, adjblock)
    return (in, inδ)
end
```

which works as expected on the CPU (still fighting with some CUDA.jl errors on the GPU). However I am bit confused why you didn't need to take a copy of the `in` register before line 3 of `backward_params!()` ( in line 135ff of apply_back.jl). Also: The whole `dropdims(sum(conj(state(...))) .* state(...),..)` business is mainly to accomodate batched register, or is it also faster than simply doing `dot(state(...), state(outδ))`?

**Comment by GiggleLiu** [comment]
Good that you find a solution to the GPU backpropagation, it tortured me for long time. FYI: if you are going to open source your project, a PR to CuYao is welcomed:
https://github.com/QuantumBFS/CuYao.jl

> However I am bit confused why you didn't need to take a copy of the in register before line 3 of backward_params!() ( in line 135ff of apply_back.jl). 

Because `out` is not useful anymore after this step in backpropagation. It is for recovering intermediate states.

>  The whole dropdims(sum(conj(state(...))) .* state(...),..) business is mainly to accomodate batched register, or is it also faster than simply doing dot(state(...), state(outδ))?

Yes.

**Comment by jlbosse** [comment]
Okay, after updating my CUDA installation it is all working now and I am getting significant speedups (about a factor of 10) from running on the GPU! Thank you very much for your help :+1:  Since I only added GPU backpropagation for `MyCustomGate` I don't think there is much point in opening a PR, but if I ever make more progress on getting GPU backpropagation working in general I will make sure to open a PR!
