### ISSUE TITLE
define my custom gate but cannot use mat function

### ISSUE THREAD

**Issue by yuyuexi** [QuantumBFS/YaoBlocks.jl#160]
Hi there, I use `Yao.jl` for my quantum computation project, where I should define a new gate with some parameters. 

After the definition of my gate and its `mat` function, I can compute the matrix of `mygate`.i.e: `mat(ComplexF64, mygate)` works well. 

However, I find error `MethodError: no method matching mat(::Type{ComplexF64}, ::mygate)`, when I use `Matrix(chain(n, mygate))` and `operator_fidelity(block, mygate)`. Did I do something incorrect?

**Comment by GiggleLiu** [comment]
Hi, you need to implement the `mat(::Type{T}, block)` to create a matrix of type element type `T`. This is lower level interface, bceause a gate does not have a specific element type. Example:
https://github.com/QuantumBFS/YaoBlocks.jl/blob/2d94a359f8a8ccca23411091243b966f4a95e56a/src/primitive/rotation_gate.jl#L90

**Comment by yuyuexi** [comment]
> Hi, you need to implement the `mat(::Type{T}, block)` to create a matrix of type element type `T`. This is lower level interface, bceause a gate does not have a specific element type. Example:
> 
> https://github.com/QuantumBFS/YaoBlocks.jl/blob/2d94a359f8a8ccca23411091243b966f4a95e56a/src/primitive/rotation_gate.jl#L90

Yeah, I  implement the `mat(::Type{T}, mygate)` as follwing
```
function mat(::Type{T}, gate::mygate{N}) where {T,N}
    m = zeros(T, 2^N, 2^N)
    for loc = 1:N-1
        m += gate.params[loc] * ( Matrix(kron(N, loc=>X, loc+1=>X)) + Matrix(kron(N, loc=>Y, loc+1=>Y)) )
    end
    return exp(1im * m)
end
```
This makes `mat(ComplexF64, mygate)` works well. But `Matrix(chain(n, mygate))` and `operator_fidelity(block, mygate)` did not work as before.

**Comment by GiggleLiu** [comment]
Do you have a minimum working example, so that I can reproduce the error?

**Comment by yuyuexi** [comment]
> Do you have a minimum working example, so that I can reproduce the error?

This is my code
```
using Yao, YaoPlots, YaoExtensions
using LinearAlgebra

mutable struct InteractionBlock{N} <: PrimitiveBlock{N}
    params::Vector{Float64}
    function InteractionBlock{N}(params::Vector) where {N} 
        @assert length(params) >= N-1 "Length of params < $(N-1) ..."
        println("Using heading $(N-1) params...")
        return new{N}(Float64.(params[1:N-1]))
    end
end

function mat(::Type{T}, gate::InteractionBlock{N}) where {T,N}
    m = zeros(T, 2^N, 2^N)
    for loc = 1:N-1
        m += gate.params[loc] * ( Matrix(kron(N, loc=>X, loc+1=>X)) + Matrix(kron(N, loc=>Y, loc+1=>Y)) )
    end
    return exp(1im * m)
end

n = 6
ig = InteractionBlock{n}([1,2,3,4,5])
cir = chain(n, ig)
mat(ComplexF64, ig)

matrix = Matrix((1.0+1.0im) * I, 2^n, 2^n)
f = operator_fidelity(matblock(matrix), ig)
```
and error captured at last line:
```
Using heading 5 params...
MethodError: no method matching mat(::Type{ComplexF64}, ::InteractionBlock{6})
Closest candidates are:
  mat(::Type{T}, ::GT) where {T, GT<:HGate} at /Users/wenjie_jiang/.julia/packages/YaoBlocks/TIlDJ/src/primitive/const_gate_tools.jl:178
  mat(::Type{T}, ::TimeEvolution{N, Tt, HT} where {Tt, HT<:AbstractBlock{N}}) where {T, N} at /Users/wenjie_jiang/.julia/packages/YaoBlocks/TIlDJ/src/primitive/time_evolution.jl:46
  mat(::Type{T}, ::FSimGate) where T at /Users/wenjie_jiang/.julia/packages/YaoExtensions/EGB9f/src/block_extension/FSimGate.jl:14
  ...

Stacktrace:
 [1] mat(x::InteractionBlock{6})
   @ YaoBlocks ~/.julia/packages/YaoBlocks/TIlDJ/src/abstract_block.jl:97
 [2] operator_fidelity(b1::GeneralMatrixBlock{6, 6, ComplexF64, Matrix{ComplexF64}}, b2::InteractionBlock{6})
   @ YaoBlocks ~/.julia/packages/YaoBlocks/TIlDJ/src/blocktools.jl:158
 [3] top-level scope
   @ In[1]:27
 [4] eval
   @ ./boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
```

Thanks for your kind reply!

**Comment by GiggleLiu** [comment]
This is the function that you need to import and overload
```julia
function YaoBlocks.mat(::Type{T}, gate::InteractionBlock{N}) where {T,N}
    m = zeros(T, 2^N, 2^N)
    for loc = 1:N-1
        m += gate.params[loc] * ( Matrix(kron(N, loc=>X, loc+1=>X)) + Matrix(kron(N, loc=>Y, loc+1=>Y)) )
    end
    return exp(1im * m)
end
```
But you created a new function called `mat` in your current module.

**Comment by yuyuexi** [comment]
> This is the function that you need to import and overload
> 
> ```julia
> function YaoBlocks.mat(::Type{T}, gate::InteractionBlock{N}) where {T,N}
>     m = zeros(T, 2^N, 2^N)
>     for loc = 1:N-1
>         m += gate.params[loc] * ( Matrix(kron(N, loc=>X, loc+1=>X)) + Matrix(kron(N, loc=>Y, loc+1=>Y)) )
>     end
>     return exp(1im * m)
> end
> ```
> 
> But you created a new function called `mat` in your current module.

ops, what a stupid mistake.

thanks, that solves my problem exactly.
