### ISSUE TITLE
how can I implement two blocks sharing same parameters?

### ISSUE THREAD

**Issue by yuyuexi** [QuantumBFS/YaoBlocks.jl#161]
Hi there. I am going to implement a quantum circuit using `Yao.jl`, which contains two blocks sharing same parameters. Let's say `U=u(a)s(b)v(a)` and `a` `b` are variational parameters in this circuit. 

1. Specifically I can implement this circuit manually and compute their gradients using some custom methods, which is also my current method. However, if the structures of `u(a)` and `v(a)` are more complex, manual implementation becomes somehow tedious and boring. 

2. I noticed that the same block instance has sharing parameters, but potentially I have different blocks in `u(a)` and `v(a)` (a specific circumstance is `u=dagger(v)` which is like VFF in [arXiv:1910.04292](https://arxiv.org/abs/1910.04292) ).

3. I also tried `Daggered` method, but it looks like it returns a new block with no sharing parameters.

4. I also thought a custom block, but in order to obtain the AD function, I have to implement `mat_back!` method, which is as complex as manual implementation.

So, is it possible to do this thing directly in `Yao.jl` and also obtain the AD function?

thanks your time!

**Comment by GiggleLiu** [comment]
For parameter sharing, you can port the gradient function to Zygote. Zygote will handle the computational graph properly for you.
Example: https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/master/examples/PortZygote/zygote_patch.jl

**Comment by yuyuexi** [comment]
> For parameter sharing, you can port the gradient function to Zygote. Zygote will handle the computational graph properly for you.
> Example: https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/master/examples/PortZygote/zygote_patch.jl

thanks your  reply!

Actually I tried this method with reference to `QuAlgorithmZoo.jl/examples/PortZygote/shared_parameters.jl`. This sample code works well. However, when I replace the `expect` function with `operator_fidelity` function, it returns an error (`Mutating arrays is not supported`), my code is just like following:
```
include("zygote_patch.jl")

import YaoExtensions, Random

c = YaoExtensions.variational_circuit(n)
h = YaoExtensions.heisenberg(n)

function loss(h, c, θ) where N
    # the assign is nessesary!
    c = dispatch!(c, fill(θ, nparameters(c)))
#     reg = apply!(zero_state(nqubits(c)), c)
#     real(expect(h, reg))
    operator_fidelity(h, c)
end

reg0 = zero_state(n)
zygote_grad = Zygote.gradient(θ->loss(h, c, θ), 0.5)[1]
==============================================
Mutating arrays is not supported

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] (::Zygote.var"#411#412")(#unused#::Nothing)
    @ Zygote ~/.julia/packages/Zygote/zowrf/src/lib/array.jl:76
  [3] (::Zygote.var"#2260#back#413"{Zygote.var"#411#412"})(Δ::Nothing)
    @ Zygote ~/.julia/packages/ZygoteRules/OjfTt/src/adjoint.jl:59
  [4] Pullback
    @ ~/.julia/packages/YaoBlocks/TIlDJ/src/routines.jl:149 [inlined]
  [5] (::typeof(∂(u1ij!)))(Δ::Nothing)
    @ Zygote ~/.julia/packages/Zygote/zowrf/src/compiler/interface2.jl:0
  [6] macro expansion
    @ ~/.julia/packages/YaoBlocks/TIlDJ/src/routines.jl:133 [inlined]
...
```

This is also the same  error I encounter in my own code. I am not  sure if I did something incorrect or how can I make it work?


ps: there might be a little typo in `QuAlgorithmZoo.jl/examples/PortZygote/shared_parameters.jl` line 25. I think you maybe mean `@test zygote_grad ≈ true_grad` but not `@test true_grad ≈ true_grad`

**Comment by GiggleLiu** [comment]
The gradient of obtaining matrix is defined to the `Matrix` function, it should be `mat` in your case:
https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/7d9743561e445a6b2044f76337f12dd445c1ddb1/examples/PortZygote/zygote_patch.jl#L20

I assumed a user would be more interested in obtaining dense matrix for gate learning. If you need sparse arrays, you might want to redefine the AD rule on `mat`. FYI, your error is because Zygote is trying to differentiate with it own AD engine, which can not handle mutating arrays.

Here is the gate learning example calling `Matrix`:
https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/master/examples/PortZygote/gate_learning.jl

**Comment by yuyuexi** [comment]
> The gradient of obtaining matrix is defined to the `Matrix` function, it should be `mat` in your case:
> https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/7d9743561e445a6b2044f76337f12dd445c1ddb1/examples/PortZygote/zygote_patch.jl#L20
> 
> I assumed a user would be more interested in obtaining dense matrix for gate learning. If you need sparse arrays, you might want to redefine the AD rule on `mat`. FYI, your error is because Zygote is trying to differentiate with it own AD engine, which can not handle mutating arrays.
> 
> Here is the gate learning example calling `Matrix`:
> https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/master/examples/PortZygote/gate_learning.jl

odd odd!

I use implementation similar to your sample code but without `g!(G,x)` method, it works perfectly. However, when I try to do this using `Zygote.gradient` and update the parameters manually, things get a little wired.

this is my code 
```
using Yao,YaoExtensions
using Zygote
using Optim

Zygote.@adjoint function Yao.dispatch!(block::AbstractBlock, params)
    out = dispatch!(block, params)
    out, function (outδ)
        (nothing, outδ)
    end
end

Zygote.@adjoint function Matrix(block::AbstractBlock)
    out = Matrix(block)
    out, function (outδ)
        paramsδ = Yao.AD.mat_back(block, outδ)
        return (paramsδ,)
    end
end

n = 4
w = chain(n, [put(n, i=>Rx(0.1)) for i = 1:n])
s = chain(n, [put(n, i=>Ry(0.2)) for i = 1:n])
u = chain(n, [w, s, w'])

w0 = chain(n, [put(n, i=>Rx(0.1)) for i = 1:n])
s0 = chain(n, [put(n, i=>Ry(0.2)) for i = 1:n])
u0 = chain(n, [w0, s0, w0'])

dispatch!(u, rand(3*n))

function foo1(params)
    p = vcat(params, -params[n:-1:1])
    Yao.dispatch!(u, p)
    - abs(tr(Matrix(u0)' * Matrix(u))) / 2^n
end

function foo2(params)
    p = vcat(params, -params[n:-1:1])
    Yao.dispatch!(u, p)
    - operator_fidelity(u0, u)
end
```

After those definitions, 
```
a = rand(2*n)
optimize(foo1, a, LBFGS(), Optim.Options(iterations=100))
println("final fidelity = $(operator_fidelity(u0, u))")
```
and
```
a = rand(2*n)
optimize(foo2, a, LBFGS(), Optim.Options(iterations=100))
println("final fidelity = $(operator_fidelity(u0, u))")
```
works very well.

but
```
gradient(foo1, a)
gradient(foo2, a)
```
returns `(nothing,)` and `Mutating arrays is not supported` error (I interpret the first one is due to my incomplete interpretation of `zygote` and the latter one is due to the reason you mentioned before). So I just write those here in case some other tiros might be confused about the same problem.

it is a good news that my problem solved, thanks for your kind reply again!

**Comment by GiggleLiu** [comment]
To fix your issue

```julia
julia> function foo1(u, params)
           p = vcat(params, -params[n:-1:1])
           u = Yao.dispatch!(u, p)
           - abs(tr(Matrix(u0)' * Matrix(u))) / 2^n
       end

julia> gradient(foo1, u, a)
(nothing, [0.015076871909998762, 0.009063743310697897, 0.009656893314551565, 0.011450201173988553, 0.07685023642276279, 0.036260728714285304, 0.08608185909545488, 0.062487755579389376])
```

I know this looks wield, but Zygote does not support mutating object. A better approach is: define a non-mutating version `dispatch`, and then define adjoint rule on that function.

## The reason why this works
```julia
a = rand(2*n)
optimize(foo1, a, LBFGS(), Optim.Options(iterations=100))
println("final fidelity = $(operator_fidelity(u0, u))")
```
It calls into finite difference. You must specify gradient function explicitly to use the gradient function you defined.

**Comment by yuyuexi** [comment]
> To fix your issue
> 
> ```julia
> julia> function foo1(u, params)
>            p = vcat(params, -params[n:-1:1])
>            u = Yao.dispatch!(u, p)
>            - abs(tr(Matrix(u0)' * Matrix(u))) / 2^n
>        end
> 
> julia> gradient(foo1, u, a)
> (nothing, [0.015076871909998762, 0.009063743310697897, 0.009656893314551565, 0.011450201173988553, 0.07685023642276279, 0.036260728714285304, 0.08608185909545488, 0.062487755579389376])
> ```
> 
> I know this looks wield, but Zygote does not support mutating object. A better approach is: define a non-mutating version `dispatch`, and then define adjoint rule on that function.
> 
> ## The reason why this works
> ```julia
> a = rand(2*n)
> optimize(foo1, a, LBFGS(), Optim.Options(iterations=100))
> println("final fidelity = $(operator_fidelity(u0, u))")
> ```
> 
> It calls into finite difference. You must specify gradient function explicitly to use the gradient function you defined.

thanks, I think your help enhances my interpretation of both `Yao.jl` and `Zygote`!
