### ISSUE TITLE
register package

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBlocks.jl#17]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register()

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register()
