### ISSUE TITLE
Preserve `chain` type signature when simplifying the circuit

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBlocks.jl#9]
Current, for simplicity in implementation, I just make use of the `Prod`'s simplification rules for `chain`, but this will cause `chain` become a `prod` after simplification.

This is not a big deal, since:

1. these two blocks are equivalent mathematically, (the only difference is that `prod` uses the order of production and is static, and chain follows the order of application with a dynamic list).
2. the process of `simplify` itself will and has to change the type, so I think it is generally fine.

But it might have some inconvenience in some cases, since `prod` is immutable while `chain` is mutable. I'll leave this issue here, to see if there's any use cases on this in the future then we shall consider change this behaviour.

**Comment by GiggleLiu** [comment]
My opinion is not mixing `chain` and `prod`. Very confusing.

**Comment by GiggleLiu** [comment]
An example of how unintuitive it can be

https://github.com/QuantumBFS/YaoBlocks.jl/issues/5

It looks like a computer with both big-endian and small-endian numbers, haha

**Comment by Roger-luo** [comment]
I think I could make a PR to make it work later, it's doable to make simplify supports chain directly. And just remove prod later.

**Comment by Roger-luo** [comment]
`chain` will not be optimized any more #5
