### ISSUE TITLE
register

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBlocks.jl#94]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register
